"use client";
import "./globals.css";
import { Provider } from "react-redux";
import store from "@/store/store";

export default function RootLayout({ children }) {
  return (
    <Provider store={store}>
      <html lang="fa">
        <head>
          <title>ویزارد</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
          <link rel="icon" href="/vizard.png" />
        </head>
        <body>
          {/* <Navbar /> */}
          <main className="mainLayout">{children}</main>
          {/* <Footer /> */}
        </body>
      </html>
    </Provider>
  );
}
