export const questions: any = [
  {
    question: "خانمی یا آقا؟ با اینکه اصلاا مهم نیس 🧒🧑",
    answer: { value_fa: ["آقا", "خانم"], value_en: ["Male", "Female"] },
    question_value: "sex",
    type: "radio",
    options: [
      { value: "Male", label: "مرد" },
      { value: "Female", label: "زن" },
    ],
  },
  {
    question: "از مدرک تحصیلیت برام بگو؟ 🔭",
    answer: {
      value_fa: ["بدون تحصیلات", "کارورزی", "دیپلم", "کارشناسی", "ارشد", "دکترا"],
      value_en: ["unedu", "apprentice", "diploma", "bachelor", "master", "phd"],
    },
    question_value: "education_field_of_study",
    type: "radio",
    options: [
      { value: "unedu", label: "بدون تحصیلات" },
      { value: "apprentice", label: "کارورزی" },
      { value: "diploma", label: "دیپلم" },
      { value: "bachelor", label: "کارشناسی" },
      { value: "master", label: "ارشد" },
      { value: "phd", label: "دکترا" },
    ],
  },
  {
    question: "کارت چیه ؟ 👷‍♀️",
    answer: {
      value_fa: ["سایر/بدون شغل", "دانش اموز/دانشجو", "بازنشسته", "کارمند", "متخصص", "مدیر"],
      value_en: ["OTHER", "student", "retired", "employee", "specialist", "manager"],
    },
    question_value: "occupation_title1",
    type: "radio",
    options: [
      { value: "OTHER", label: "سایر/بدون شغل" },
      { value: "student", label: "دانش اموز/دانشجو" },
      { value: "retired", label: "بازنشسته" },
      { value: "employee", label: "کارمند" },
      { value: "specialist", label: "متخصص" },
      { value: "manager", label: "مدیر" },
    ],
  },
  {
    question: "تا حالا از جایی دیپورت شدی؟ 💀",
    answer: { value_fa: ["بله", "خیر"], value_en: ["true", "false"] },
    question_value: "refused_entry_or_deport",
    type: "radio",
    options: [
      { value: "true", label: "بله" },
      { value: "false", label: "خیر" },
    ],
  },
  {
    question: "چند سالته؟ واقعی بگیاا 🔞",
    answer: { value_fa: [18, 50] },
    question_value: "date_of_birth",
    type: "number",
    // step: "",
    options: [
      { value: 18, label: 18 },
      { value: 50, label: 50 },
    ],
  },
  {
    question: " وضعیت تاهل ؟ 💍/🦅",
    answer: {
      value_fa: ["مجرد", "مزدوج", "مطلقه", "بیوه", "سایر"],
      value_en: ["single", "married", "divorced", "widowed", "unknown"],
    },
    question_value: "applicant_marital_status",
    type: "radio",
    options: [
      { value: "single", label: "مجرد" },
      { value: "married", label: "مزدوج" },
      { value: "divorced", label: "مطلقه" },
      { value: "widowed", label: "بیوه" },
      { value: "unknown", label: "سایر" },
    ],
  },
  {
    question: "چند وقته متاهلی؟ ⌛💍",
    answer: { value_fa: [0, 50] },
    question_value: "marriage_period",
    type: "number",
    step: 5,
    options: [
      { value: 0, label: 0 },
      { value: 50, label: 50 },
    ],
  },
  {
    question: "چند سال تو آخرین شغلت، مشغول  به کار بودی؟ 🤔",
    answer: { value_fa: [0, 35] },
    question_value: "occupation_period",
    type: "number",
    step: 5,
    options: [
      { value: 0, label: 0 },
      { value: 70, label: 70 },
    ],
  },
  {
    question: " چند نفر از فرزندات تو رو همراهی میکنن؟👶",
    answer: { value_fa: [0, 4] },
    question_value: "child_accompany",
    type: "number",
    step: 1,
    options: [
      { value: 0, label: 0 },
      { value: 4, label: 4 },
    ],
  },
  {
    question: "چه افرادی را همراه خود می برید؟ 👪",
    answer: {
      value_fa: ["هیچ‌کدام", "پدر و مادر با یکدیگر", "فقط پدر / مادر"],
      value_en: ["0", "1", "2"],
      key_en: ["parent_accompany", "parent_accompany", "parent_accompany"]
    },
    question_value: "parent_accompany",
    type: "radio_unique",
    options: [
      { value: "0", label: "هیچ‌کدام", key: "parent_accompany" },
      { value: "1", label: "پدر و مادر با یکدیگر", key: "parent_accompany" },
      { value: "2", label: "فقط پدر / مادر", key: "parent_accompany" },
    ],
  },
  {
    question: "همسرتم میبری دیگه؟👀🔪 ",
    answer: { value_fa: ["بله", "خیر"], value_en: [1, 0] },
    question_value: "spouse_accompany",
    type: "radio",
    options: [
      { value: 1, label: "بله" },
      { value: 0, label: "خیر" },
    ],
  },
  {
    question: "چند نفر از خواهر ، برادرات میان؟👨‍👨‍👦‍👦 ",
    answer: { value_fa: [0, 7] },
    question_value: "sibling_accompany",
    type: "number",
    step: 1,
    options: [
      { value: 0, label: 0 },
      { value: 7, label: 7 },
    ],
  },
  {
    question: "صاحب چند تا فرزندی؟🍼 ",
    answer: { value_fa: [0, 4] },
    question_value: "child_count",
    type: "number",
    step: 1,
    options: [
      { value: 0, label: 0 },
      { value: 11, label: 11 },
    ],
  },
  //new
  {
    question: "چقدر میخوای برای هر نفر همراهت سر کیسه رو شل کنی؟ 💰 (100 - 600 دلار)",
    answer: { value_fa: [100, 600] },
    question_value: "bank_balance",
    type: "number",
    step: 10,
  },
  {
    question: "آیا دعوتنامه داری؟",
    answer: {
      value_en: [
        "child",
        "sibling",
        "parent",
        "f2",
        "f3",
        "friend",
        "spouse",
        "pro_unrelated",
        "pro_related",
        "none",
      ],
      value_fa: [
        "فرزندان",
        "خواهر و برادر",
        "پدر و مادر",
        "اقوام درجه دو",
        "اقوام درجه سه",
        "دوست",
        "همسر",
        "حرفه ای غیر مرتبط",
        "حرفه ای مرتبط",
        "هیچی 😶",
      ],
    },
    question_value: "invitation_letter",
    type: "radio",
    options: [
      { value: "child", label: "فرزندان" },
      { value: "sibling", label: "خواهر و برادر" },
      { value: "parent", label: "پدر و مادر" },
      { value: "f2", label: "اقوام درجه دو" },
      { value: "f3", label: "اقوام درجه سه" },
      { value: "friend", label: "دوست" },
      { value: "spouse", label: "همسر" },
      { value: "pro_unrelated", label: "حرفه ای غیر مرتبط" },
      { value: "pro_related", label: "حرفه ای مرتبط" },
      { value: "none", label: "هیچی 😶" },
    ],
  },
  {
    question: "امیدوارم سابقه دار باشی. البته از نوع سفری!",
    answer: {
      value_en: [
        "schengen_once",
        "schengen_twice",
        "us_uk_au",
        "jp_kr_af",
        "br_sg_th_my_ru",
        "ae_om_qa",
        "am_ge_tr_az",
        "none",
      ],
      value_fa: [
        "یکبار شنگن",
        "دوبار و بیشتر شنگن",
        "آمریکا ، انگلیس ، استرالیا",
        "ژاپن ، کره ، آفریقا",
        "برزیل ، سنگاپور ، تایلند ، مالزی ، روسیه",
        "امارات ، عمان ، قطر",
        "ارمنستان ، گرجستان ، ترکیه ، آذربایجان",
        "هیچی 😶",
      ],
    },

    question_value: "travel_history",
    type: "radio_multi",
    options: [
      { value: "schengen_once", label: "یکبار شنگن" },
      { value: "schengen_twice", label: "دوبار و بیشتر شنگن" },
      { value: "us_uk_au", label: "آمریکا ، انگلیس ، استرالیا" },
      { value: "jp_kr_af", label: "ژاپن ، کره ، آفریقا" },
      { value: "br_sg_th_my_ru", label: "برزیل ، سنگاپور ، تایلند ، مالزی ، روسیه" },
      { value: "ae_om_qa", label: "امارات ، عمان ، قطر" },
      { value: "am_ge_tr_az", label: "ارمنستان ، گرجستان ، ترکیه ، آذربایجان" },
      { value: "none", label: "هیچی 😶" },
    ],
  },
];
